<%
	' CREDENTIALS
	Const OAUTH_EXAMPLE_CONSUMER_KEY		= "CjOsOkDaqmTUd06jCYq5A"
	Const OAUTH_EXAMPLE_CONSUMER_SECRET		= "OS99hOKS0t4jGLp5nYVmTetjh4ZET8OW5Rej8Xw"

	' OPTIONS
	Const OAUTH_EXAMPLE_FORCE_LOGIN			= True

	' CALLBACK URL
	Const OAUTH_EXAMPLE_CALLBACK_URL		= "http://localhost:8383/twitter/callback.asp" 'PROD

	' REDIRECT URLS
	Const OAUTH_EXAMPLE_ERROR_URL			= "error.asp"
	Const OAUTH_EXAMPLE_LOGIN_FAILURE_URL	= "log_in_failure.asp"
	Const OAUTH_EXAMPLE_LOGIN_SUCCESS_URL	= "log_in_success.asp"
	Const OAUTH_EXAMPLE_TIMEOUT_URL			= "timeout.asp"
%>